import { firebaseConfig } from "./firebase-config.js";

const FIREBASE_VERSION = "10.12.2";
const FIREBASE_BASE = `https://www.gstatic.com/firebasejs/${FIREBASE_VERSION}`;

const state = {
  user: null, auth: null, db: null, f: null,
  memberships: [], activeMembership: null,
  chanda: [], kharcha: [], members: [], requests: [],
  editingChandaId: null, editingKharchaId: null,
  unsubscribers: [], membershipUnsubscribe: null,
  lang: localStorage.getItem("devnidhi-lang") || "hi"
};

const $ = (selector) => document.querySelector(selector);
const elements = {
  loading: $("#loading-overlay"), offlineBanner: $("#offline-banner"), configBanner: $("#config-banner"),
  toastContainer: $("#toast-container"), accountButton: $("#account-button"), logoutButton: $("#logout-button"),
  bottomNav: $("#bottom-nav"), screens: document.querySelectorAll(".screen"), navButtons: document.querySelectorAll(".nav-button"), langButtons: document.querySelectorAll(".lang-button"),
  workspaceBar: $("#workspace-bar"), workspaceName: $("#workspace-name"), workspaceRole: $("#workspace-role"), workspaceId: $("#workspace-id"),
  chandaAdminPanel: $("#chanda-admin-panel"), kharchaAdminPanel: $("#kharcha-admin-panel"), chandaForm: $("#chanda-form"), kharchaForm: $("#kharcha-form"),
  chandaList: $("#chanda-list"), kharchaList: $("#kharcha-list"), chandaSearch: $("#chanda-search"), kharchaSearch: $("#kharcha-search"), chandaCancel: $("#chanda-cancel"), kharchaCancel: $("#kharcha-cancel"),
  createTempleForm: $("#create-temple-form"), joinTempleForm: $("#join-temple-form"), templeSwitcher: $("#temple-switcher"), myTemplesCard: $("#my-temples-card"), activeTempleCard: $("#active-temple-card"),
  renameTempleForm: $("#rename-temple-form"), renameTempleInput: $("#rename-temple-input"), requestsCard: $("#requests-card"), requestsList: $("#requests-list"), membersCard: $("#members-card"), membersList: $("#members-list")
};

const i18n = {
  hi: {
    appTagline: "Mandir Nirman Kosh", signIn: "Sign in", account: "Account", logout: "Logout",
    offline: "आप ऑफलाइन हैं - पहले से synced mandir data दिख रहा है।", config: "Firebase project credentials firebase-config.js में जोड़ें ताकि DevNidhi cloud से जुड़ सके।",
    workspace: "Mandir Workspace", dashboardTitle: "भक्ति की गरमाहट, हिसाब की स्पष्टता।", dashboardSubtitle: "अपने mandir ka chanda, kharcha aur shesh rashi ek secure jagah par sambhalein.",
    totalChanda: "कुल चंदा", totalKharcha: "कुल खर्च", balance: "शेष राशि", totalDonors: "कुल दानदाता", expenseEntries: "खर्च प्रविष्टियां",
    chanda: "चंदा", chandaSubtitle: "दानदाता, राशि, तारीख और भुगतान माध्यम साफ-साफ दर्ज करें।", addChanda: "नया चंदा जोड़ें", editChanda: "चंदा संपादित करें", saveChanda: "चंदा सेव करें", updateChanda: "चंदा अपडेट करें", allChanda: "सभी चंदा रिकॉर्ड", donorName: "दानदाता का नाम", amount: "राशि ₹", date: "दिनांक", paymentMode: "Payment Mode", note: "नोट (वैकल्पिक)", searchDonor: "दानदाता खोजें...", noChanda: "अभी कोई चंदा रिकॉर्ड नहीं है।", noMatchingDonor: "मिलता-जुलता दानदाता नहीं मिला।",
    kharcha: "खर्च", kharchaSubtitle: "Mandir sambandhit kharcha category ke saath record करें।", addKharcha: "नया खर्च जोड़ें", editKharcha: "खर्च संपादित करें", saveKharcha: "खर्च सेव करें", updateKharcha: "खर्च अपडेट करें", allKharcha: "सभी खर्च रिकॉर्ड", description: "विवरण", category: "Category", searchKharcha: "खर्च खोजें...", noKharcha: "अभी कोई खर्च रिकॉर्ड नहीं है।", noMatchingExpense: "मिलता-जुलता खर्च नहीं मिला।",
    accountTitle: "DevNidhi में स्वागत है", accountSubtitle: "अपने mandir ke hisaab ko सुरक्षित तरीके से manage करें।", google: "Continue with Google", privacy: "आपका mandir data Firebase में सुरक्षित रहता है और आपके Google account से जुड़ा होता है।", about: "DevNidhi के बारे में", aboutTitle: "Mandir chanda, kharcha aur team access ke liye ek saaf aur bharosemand control room.", aboutBody: "DevNidhi mandir committee ko chanda, kharcha, members aur access requests ek secure workspace mein organized rakhne mein madad karta hai.",
    templeTitle: "Mandir Workspace", templeSubtitle: "Mandir workspace चुनें, team members जोड़ें और access manage करें।", createTemple: "Mandir Workspace बनाएं", joinTemple: "Workspace join करें", templeName: "Mandir ka naam", templePlaceholder: "जैसे Shri Ram Mandir", workspaceId: "Workspace ID", workspacePlaceholder: "Owner द्वारा share किया Workspace ID paste करें", createWorkspace: "Workspace बनाएं", requestAccess: "Access request भेजें", myTemples: "मेरे Mandir Workspaces", renameTemple: "Mandir ka naam", saveNewName: "नया नाम सेव करें", shareWorkspace: "यह Workspace ID share करें", copyId: "ID copy करें", workspaceHelp: "New team members is ID se access request karte hain. Records dekhne se pehle owner approval zaroori hai.", pendingRequests: "Pending Access Requests", teamMembers: "Team Members",
    owner: "Owner", admin: "Admin", viewer: "Viewer", member: "Member", user: "User", approveAdmin: "Admin approve", approveViewer: "Viewer", noMembers: "अभी कोई member नहीं है।", noRequests: "कोई pending request नहीं है।", cancel: "रद्द करें", navDashboard: "डैशबोर्ड", navChanda: "दान", navKharcha: "खर्च", navTemple: "Mandir", loading: "DevNidhi loading...",
    cash: "Cash", online: "Online", cheque: "Cheque", material: "Material", labour: "Labour", puja: "Puja", utilities: "Utilities", other: "Other",
    openingGoogle: "Google खुल रहा है...", creating: "बन रहा है...", sending: "भेजा जा रहा है...", saving: "सेव हो रहा है...", signedOut: "Signed out.", backOnline: "Back online - data sync ho raha hai.", firebaseStartError: "Firebase start नहीं हो सका।", validAmount: "कृपया सही राशि डालें।", chandaSaved: "चंदा सेव हो गया।", kharchaSaved: "खर्च सेव हो गया।", entryDeleted: "Entry delete हो गई।", deleteConfirm: "इस entry को permanently delete करें?", rejectConfirm: "इस access request को reject करें?", removeConfirm: "ko mandir se remove करें?", copied: "Workspace ID copy हो गया।", created: "Temple workspace बन गया।", createFailed: "Workspace create नहीं हो सका। Firestore rules check करें।", accessSent: "Access request भेज दी गई। Owner से approval के लिए कहें।", notFound: "Workspace ID नहीं मिला।", alreadyMember: "आप पहले से इस mandir में member हैं।", requestFailed: "Request भेजी नहीं जा सकी।", approved: "Member approve हो गया।", approveFailed: "Member approve नहीं हो सका।", nameUpdated: "Temple name sabhi members ke liye update ho gaya.", nameFailed: "Temple name update नहीं हो सका।", sameName: "Ye already current temple name hai.", roleChanged: "Role update ho gaya.", roleFailed: "Member role change nahi ho saka.", removed: "Member removed.", removeFailed: "Member remove nahi ho saka.", chandaSaveFailed: "चंदा सेव नहीं हो सका।", kharchaSaveFailed: "खर्च सेव नहीं हो सका।", deleteFailed: "Entry delete नहीं हो सकी।", cloudDenied: "आपको इस workspace ka access nahi hai.", cloudLoad: "Cloud data load नहीं हो सका।"
  },
  en: {
    appTagline: "Mandir Nirman Kosh", signIn: "Sign in", account: "Account", logout: "Logout",
    offline: "You are offline - previously synced mandir data is being shown.", config: "Add Firebase project credentials in firebase-config.js to connect DevNidhi.",
    workspace: "Mandir Workspace", dashboardTitle: "Warmth of devotion, clarity of accounts.", dashboardSubtitle: "Manage donations, expenses and balance for your mandir in one secure place.",
    totalChanda: "Total Donations", totalKharcha: "Total Expenses", balance: "Balance", totalDonors: "Total Donors", expenseEntries: "Expense Entries",
    chanda: "Donations", chandaSubtitle: "Record donor, amount, date and payment mode clearly.", addChanda: "Add Donation", editChanda: "Edit Donation", saveChanda: "Save Donation", updateChanda: "Update Donation", allChanda: "All Donations", donorName: "Donor Name", amount: "Amount ₹", date: "Date", paymentMode: "Payment Mode", note: "Note (optional)", searchDonor: "Search donor...", noChanda: "No donation entries yet.", noMatchingDonor: "No matching donor found.",
    kharcha: "Expenses", kharchaSubtitle: "Record mandir expenses with categories and notes.", addKharcha: "Add Expense", editKharcha: "Edit Expense", saveKharcha: "Save Expense", updateKharcha: "Update Expense", allKharcha: "All Expenses", description: "Description", category: "Category", searchKharcha: "Search expenses...", noKharcha: "No expense entries yet.", noMatchingExpense: "No matching expense found.",
    accountTitle: "Welcome to DevNidhi", accountSubtitle: "Continue securely to manage your mandir accounts.", google: "Continue with Google", privacy: "Your mandir records stay protected in Firebase and linked to your Google account.", about: "About DevNidhi", aboutTitle: "A clean control room for mandir donations, expenses and team access.", aboutBody: "DevNidhi helps mandir committees keep donations, expenses, members and access requests organized in one secure workspace.",
    templeTitle: "Mandir Workspace", templeSubtitle: "Choose a mandir workspace, add team members and manage access.", createTemple: "Create Mandir Workspace", joinTemple: "Join Workspace", templeName: "Mandir Name", templePlaceholder: "e.g. Shri Ram Mandir", workspaceId: "Workspace ID", workspacePlaceholder: "Paste the Workspace ID shared by the owner", createWorkspace: "Create Workspace", requestAccess: "Request Access", myTemples: "My Mandir Workspaces", renameTemple: "Mandir Name", saveNewName: "Save New Name", shareWorkspace: "Share this Workspace ID", copyId: "Copy ID", workspaceHelp: "New team members request access with this ID. The owner must approve them before they can see records.", pendingRequests: "Pending Access Requests", teamMembers: "Team Members",
    owner: "Owner", admin: "Admin", viewer: "Viewer", member: "Member", user: "User", approveAdmin: "Approve Admin", approveViewer: "Viewer", noMembers: "No members found.", noRequests: "No pending requests.", cancel: "Cancel Edit", navDashboard: "Dashboard", navChanda: "Donations", navKharcha: "Expenses", navTemple: "Mandir", loading: "Loading DevNidhi...",
    cash: "Cash", online: "Online", cheque: "Cheque", material: "Material", labour: "Labour", puja: "Puja", utilities: "Utilities", other: "Other",
    openingGoogle: "Opening Google...", creating: "Creating...", sending: "Sending...", saving: "Saving...", signedOut: "Signed out.", backOnline: "Back online - syncing data.", firebaseStartError: "Firebase could not start.", validAmount: "Enter a valid amount.", chandaSaved: "Donation saved.", kharchaSaved: "Expense saved.", entryDeleted: "Entry deleted.", deleteConfirm: "Delete this entry permanently?", rejectConfirm: "Reject this access request?", removeConfirm: "from the temple?", copied: "Workspace ID copied.", created: "Temple workspace created.", createFailed: "Workspace could not be created. Check Firestore rules.", accessSent: "Access requested. Ask the temple owner to approve you.", notFound: "Workspace ID was not found.", alreadyMember: "You already belong to this temple.", requestFailed: "Request could not be sent.", approved: "Member approved.", approveFailed: "Member could not be approved.", nameUpdated: "Temple name updated for all members.", nameFailed: "Temple name could not be updated.", sameName: "This is already the current temple name.", roleChanged: "Role updated.", roleFailed: "Member role could not be changed.", removed: "Member removed.", removeFailed: "Member could not be removed.", chandaSaveFailed: "Donation could not be saved.", kharchaSaveFailed: "Expense could not be saved.", deleteFailed: "Entry could not be deleted.", cloudDenied: "You do not have permission to access this workspace.", cloudLoad: "Cloud data could not be loaded."
  }
};

const money = new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 2 });
const t = (key) => i18n[state.lang]?.[key] || i18n.hi[key] || key;
const formatCurrency = (value) => money.format(Number(value) || 0);
const today = () => { const d = new Date(); return new Date(d.getTime() - d.getTimezoneOffset() * 60000).toISOString().slice(0, 10); };
const escapeHtml = (value = "") => String(value).replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#039;");
const formatDate = (value) => { const d = value?.toDate ? value.toDate() : new Date(value); return Number.isNaN(d.getTime()) ? "-" : new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "2-digit", year: "numeric" }).format(d); };
const inputDate = (value) => { const d = value?.toDate ? value.toDate() : new Date(value); if (Number.isNaN(d.getTime())) return today(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`; };
const canEdit = () => ["owner", "admin"].includes(state.activeMembership?.role);
const isOwner = () => state.activeMembership?.role === "owner";
const displayRole = (role = "viewer") => t(role) || role;
const displayPaymentMode = (mode = "") => ({ Cash: t("cash"), Online: t("online"), Cheque: t("cheque") }[mode] || mode);
const displayCategory = (category = "") => ({ Material: t("material"), Labour: t("labour"), Puja: t("puja"), Utilities: t("utilities"), Other: t("other"), Flights: t("material"), Hotels: t("labour"), Visa: t("puja"), Transport: t("utilities") }[category] || category);
const editIcon = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 20h9"/><path d="M16.5 3.5a2.1 2.1 0 0 1 3 3L8 18l-4 1 1-4Z"/></svg>';
const deleteIcon = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M3 6h18M8 6V4h8v2M6 6l1 15h10l1-15M10 10v7M14 10v7"/></svg>';

function textNode(selector, value) { const node = $(selector); if (node) node.textContent = value; }
function labelFor(id, value) { textNode(`label[for="${id}"]`, value); }
function placeholderFor(id, value) { const node = $(`#${id}`); if (node) node.placeholder = value; }
function setButtonLabel(button, value) {
  if (!button) return;
  const text = Array.from(button.childNodes).find((node) => node.nodeType === Node.TEXT_NODE && node.textContent.trim());
  if (text) text.textContent = `\n${value}\n`;
  else button.append(value);
}
function toast(message, type = "") { const node = document.createElement("div"); node.className = `toast ${type}`.trim(); node.textContent = message; elements.toastContainer.appendChild(node); setTimeout(() => node.remove(), 4000); }
function busy(button, enabled, label) { if (!button) return; if (enabled) { button.dataset.label = button.textContent; button.textContent = label; button.disabled = true; } else { button.textContent = button.dataset.label || button.textContent; button.disabled = false; } }

function applyLanguage() {
  document.documentElement.lang = state.lang === "hi" ? "hi" : "en";
  elements.langButtons.forEach((button) => button.classList.toggle("active", button.dataset.lang === state.lang));
  textNode("#offline-banner", t("offline")); textNode("#config-banner", t("config")); textNode(".brand-tagline", t("appTagline"));
  textNode("#workspace-label-main", t("workspace")); textNode("#dashboard-title", t("dashboardTitle")); textNode("#dashboard-subtitle", t("dashboardSubtitle"));
  textNode(".summary-card.donation .summary-label", t("totalChanda")); textNode(".summary-card.expense .summary-label", t("totalKharcha")); textNode(".summary-card.balance .summary-label", t("balance"));
  textNode(".stats-grid .stat-card:nth-child(1) .stat-label", t("totalDonors")); textNode(".stats-grid .stat-card:nth-child(2) .stat-label", t("expenseEntries"));
  textNode("#chanda-title", t("chanda")); textNode("#chanda-subtitle", t("chandaSubtitle")); textNode("#kharcha-title", t("kharcha")); textNode("#kharcha-subtitle", t("kharchaSubtitle"));
  labelFor("donor-name", t("donorName")); labelFor("chanda-amount", t("amount")); labelFor("chanda-date", t("date")); labelFor("payment-mode", t("paymentMode")); labelFor("chanda-note", t("note"));
  labelFor("expense-description", t("description")); labelFor("kharcha-amount", t("amount")); labelFor("kharcha-date", t("date")); labelFor("expense-category", t("category")); labelFor("kharcha-note", t("note"));
  textNode("#chanda-form-title", state.editingChandaId ? t("editChanda") : t("addChanda")); textNode("#kharcha-form-title", state.editingKharchaId ? t("editKharcha") : t("addKharcha"));
  textNode("#chanda-submit", state.editingChandaId ? t("updateChanda") : t("saveChanda")); textNode("#kharcha-submit", state.editingKharchaId ? t("updateKharcha") : t("saveKharcha")); textNode("#chanda-cancel", t("cancel")); textNode("#kharcha-cancel", t("cancel"));
  textNode("#chanda-screen .list-toolbar h3", t("allChanda")); textNode("#kharcha-screen .list-toolbar h3", t("allKharcha")); placeholderFor("chanda-search", t("searchDonor")); placeholderFor("kharcha-search", t("searchKharcha"));
  textNode("#account-title", t("accountTitle")); textNode("#account-subtitle", t("accountSubtitle")); setButtonLabel($("#google-signin-button"), t("google")); textNode(".login-card .privacy-note", t("privacy")); textNode(".about-kicker", t("about")); textNode("#about-devnidhi-title", t("aboutTitle")); textNode(".about-card > p", t("aboutBody"));
  textNode("#temple-title", t("templeTitle")); textNode("#temple-subtitle", t("templeSubtitle")); textNode("#workspace-onboarding .section-card:nth-child(1) .section-title", t("createTemple")); textNode("#workspace-onboarding .section-card:nth-child(2) .section-title", t("joinTemple"));
  labelFor("temple-name-input", t("templeName")); labelFor("temple-id-input", t("workspaceId")); placeholderFor("temple-name-input", t("templePlaceholder")); placeholderFor("temple-id-input", t("workspacePlaceholder")); textNode("#create-temple-form .primary-button", t("createWorkspace")); textNode("#join-temple-form .secondary-button", t("requestAccess")); textNode("#my-temples-card .section-title", t("myTemples")); labelFor("rename-temple-input", t("renameTemple")); textNode("#rename-temple-form .primary-button", t("saveNewName")); textNode("#active-temple-card .workspace-label", t("shareWorkspace")); textNode("#copy-workspace-id", t("copyId")); textNode("#active-temple-card .privacy-note", t("workspaceHelp")); textNode("#requests-card .section-title", t("pendingRequests")); textNode("#members-card .section-title", t("teamMembers"));
  setButtonLabel(document.querySelector('[data-screen="dashboard"]'), t("navDashboard")); setButtonLabel(document.querySelector('[data-screen="chanda"]'), t("navChanda")); setButtonLabel(document.querySelector('[data-screen="kharcha"]'), t("navKharcha")); setButtonLabel(document.querySelector('[data-screen="temple"]'), t("navTemple")); textNode("#loading-overlay span", t("loading")); textNode("#logout-button", t("logout"));
  const paymentOptions = { Cash: t("cash"), Online: t("online"), Cheque: t("cheque") }; document.querySelectorAll("#payment-mode option").forEach((option) => { option.textContent = paymentOptions[option.value] || option.value; });
  const categoryOptions = { Material: t("material"), Labour: t("labour"), Puja: t("puja"), Utilities: t("utilities"), Other: t("other") }; document.querySelectorAll("#expense-category option").forEach((option) => { option.textContent = categoryOptions[option.value] || option.value; });
  renderAccount();
}
function setLanguage(lang) { if (!["hi", "en"].includes(lang) || state.lang === lang) return; state.lang = lang; localStorage.setItem("devnidhi-lang", lang); applyLanguage(); renderWorkspace(); }
function showScreen(name) { if (!state.user && name !== "account") name = "account"; if (state.user && !state.activeMembership && !["temple", "account"].includes(name)) name = "temple"; elements.screens.forEach((screen) => screen.classList.toggle("active", screen.id === `${name}-screen`)); elements.navButtons.forEach((button) => button.classList.toggle("active", button.dataset.screen === name)); elements.bottomNav.classList.toggle("hidden", !state.user || name === "account"); window.scrollTo({ top: 0, behavior: "smooth" }); }
function firebaseConfigured() { return ["apiKey", "authDomain", "projectId", "appId"].every((key) => firebaseConfig[key] && !String(firebaseConfig[key]).startsWith("YOUR_")); }
function timestampFromInput(value) { return state.f.Timestamp.fromDate(new Date(`${value}T12:00:00`)); }
function membershipId(uid, templeId) { return `${uid}_${templeId}`; }

function renderDashboard() { const donations = state.chanda.reduce((sum, x) => sum + Number(x.amount || 0), 0); const expenses = state.kharcha.reduce((sum, x) => sum + Number(x.amount || 0), 0); const donors = new Set(state.chanda.map((x) => String(x.donorName || "").trim().toLowerCase()).filter(Boolean)); $("#total-chanda").textContent = formatCurrency(donations); $("#total-kharcha").textContent = formatCurrency(expenses); $("#net-balance").textContent = formatCurrency(donations - expenses); $("#total-donors").textContent = donors.size; $("#total-expenses").textContent = state.kharcha.length; }
function renderChanda() { const term = elements.chandaSearch.value.trim().toLowerCase(); const rows = state.chanda.filter((x) => String(x.donorName || "").toLowerCase().includes(term)); elements.chandaList.innerHTML = rows.length ? rows.map((x) => `<article class="entry-card"><div class="entry-main"><div class="entry-title-row"><h4 class="entry-title">${escapeHtml(x.donorName)}</h4><p class="entry-amount income">${formatCurrency(x.amount)}</p></div><div class="entry-meta"><span class="meta-chip">${formatDate(x.date)}</span><span class="meta-chip">${escapeHtml(displayPaymentMode(x.paymentMode))}</span></div>${x.note ? `<p class="entry-note">${escapeHtml(x.note)}</p>` : ""}</div>${canEdit() ? `<div class="entry-actions"><button class="icon-button" data-action="edit-chanda" data-id="${x.id}" aria-label="${t("editChanda")}">${editIcon}</button><button class="icon-button delete" data-action="delete-chanda" data-id="${x.id}" aria-label="Delete donation">${deleteIcon}</button></div>` : ""}</article>`).join("") : `<div class="empty-state">${term ? t("noMatchingDonor") : t("noChanda")}</div>`; }
function renderKharcha() { const term = elements.kharchaSearch.value.trim().toLowerCase(); const rows = state.kharcha.filter((x) => String(x.description || "").toLowerCase().includes(term)); elements.kharchaList.innerHTML = rows.length ? rows.map((x) => `<article class="entry-card"><div class="entry-main"><div class="entry-title-row"><h4 class="entry-title">${escapeHtml(x.description)}</h4><p class="entry-amount outgoing">${formatCurrency(x.amount)}</p></div><div class="entry-meta"><span class="meta-chip">${formatDate(x.date)}</span><span class="meta-chip">${escapeHtml(displayCategory(x.category))}</span></div>${x.note ? `<p class="entry-note">${escapeHtml(x.note)}</p>` : ""}</div>${canEdit() ? `<div class="entry-actions"><button class="icon-button" data-action="edit-kharcha" data-id="${x.id}" aria-label="${t("editKharcha")}">${editIcon}</button><button class="icon-button delete" data-action="delete-kharcha" data-id="${x.id}" aria-label="Delete expense">${deleteIcon}</button></div>` : ""}</article>`).join("") : `<div class="empty-state">${term ? t("noMatchingExpense") : t("noKharcha")}</div>`; }
function renderWorkspace() { const active = state.activeMembership; elements.workspaceBar.classList.toggle("hidden", !active); elements.chandaAdminPanel.classList.toggle("hidden", !canEdit()); elements.kharchaAdminPanel.classList.toggle("hidden", !canEdit()); elements.myTemplesCard.classList.toggle("hidden", !state.memberships.length); elements.activeTempleCard.classList.toggle("hidden", !active); elements.membersCard.classList.toggle("hidden", !active); elements.renameTempleForm.classList.toggle("hidden", !active || !isOwner()); elements.requestsCard.classList.toggle("hidden", !active || !isOwner()); if (active) { elements.workspaceName.textContent = active.templeName; elements.workspaceRole.textContent = displayRole(active.role); elements.workspaceId.textContent = active.templeId; elements.renameTempleInput.value = active.templeName; } elements.templeSwitcher.innerHTML = state.memberships.map((m) => `<button class="temple-choice ${m.templeId === active?.templeId ? "active" : ""}" data-temple-id="${m.templeId}"><strong>${escapeHtml(m.templeName)}</strong><span>${escapeHtml(displayRole(m.role))}</span></button>`).join(""); elements.membersList.innerHTML = state.members.length ? state.members.map((m) => { const owner = m.role === "owner"; const roleControl = isOwner() && !owner ? `<div class="member-controls"><select class="role-select" data-action="change-role" data-member-id="${m.id}" aria-label="Role for ${escapeHtml(m.displayName || m.email || t("member"))}"><option value="admin" ${m.role === "admin" ? "selected" : ""}>${t("admin")}</option><option value="viewer" ${m.role === "viewer" ? "selected" : ""}>${t("viewer")}</option></select><button class="icon-button delete" data-action="remove-member" data-member-id="${m.id}" aria-label="Remove member">x</button></div>` : `<span class="role-badge">${escapeHtml(displayRole(m.role))}</span>`; return `<article class="member-row"><div><strong>${escapeHtml(m.displayName || m.email || t("member"))}</strong><span>${escapeHtml(m.email || "")}</span></div>${roleControl}</article>`; }).join("") : `<div class="empty-state">${t("noMembers")}</div>`; elements.requestsList.innerHTML = state.requests.length ? state.requests.map((r) => `<article class="member-row"><div><strong>${escapeHtml(r.displayName || r.email || t("user"))}</strong><span>${escapeHtml(r.email || "")}</span></div><div class="approval-actions"><button class="primary-button compact" data-action="approve" data-role="admin" data-uid="${r.uid}">${t("approveAdmin")}</button><button class="secondary-button compact" data-action="approve" data-role="viewer" data-uid="${r.uid}">${t("approveViewer")}</button><button class="icon-button delete" data-action="reject" data-uid="${r.uid}" aria-label="Reject request">x</button></div></article>`).join("") : `<div class="empty-state">${t("noRequests")}</div>`; renderDashboard(); renderChanda(); renderKharcha(); }
function renderAccount() { elements.accountButton.textContent = state.user ? (state.user.displayName || t("account")) : t("signIn"); elements.logoutButton.classList.toggle("hidden", !state.user); if (!state.user) { elements.workspaceBar.classList.add("hidden"); elements.bottomNav.classList.add("hidden"); } }
function clearWorkspaceListeners() { state.unsubscribers.forEach((unsub) => unsub()); state.unsubscribers = []; state.chanda = []; state.kharcha = []; state.members = []; state.requests = []; }
function activateTemple(membership) { clearWorkspaceListeners(); state.activeMembership = membership || null; resetChanda(); resetKharcha(); renderWorkspace(); if (!membership) { showScreen("temple"); elements.loading.classList.add("hidden"); return; } const tid = membership.templeId; const { collection, query, where, orderBy, onSnapshot } = state.f; state.unsubscribers.push(onSnapshot(query(collection(state.db, "temples", tid, "chanda"), orderBy("date", "desc")), (snap) => { state.chanda = snap.docs.map((d) => ({ id: d.id, ...d.data() })); renderDashboard(); renderChanda(); }, firestoreError)); state.unsubscribers.push(onSnapshot(query(collection(state.db, "temples", tid, "kharcha"), orderBy("date", "desc")), (snap) => { state.kharcha = snap.docs.map((d) => ({ id: d.id, ...d.data() })); renderDashboard(); renderKharcha(); }, firestoreError)); state.unsubscribers.push(onSnapshot(query(collection(state.db, "memberships"), where("templeId", "==", tid)), (snap) => { state.members = snap.docs.map((d) => ({ id: d.id, ...d.data() })); renderWorkspace(); }, firestoreError)); if (membership.role === "owner") state.unsubscribers.push(onSnapshot(collection(state.db, "temples", tid, "joinRequests"), (snap) => { state.requests = snap.docs.map((d) => ({ id: d.id, ...d.data() })); renderWorkspace(); }, firestoreError)); renderWorkspace(); elements.loading.classList.add("hidden"); }
function subscribeMemberships() { if (state.membershipUnsubscribe) state.membershipUnsubscribe(); const q = state.f.query(state.f.collection(state.db, "memberships"), state.f.where("uid", "==", state.user.uid)); state.membershipUnsubscribe = state.f.onSnapshot(q, { includeMetadataChanges: true }, (snap) => { state.memberships = snap.docs.map((d) => ({ id: d.id, ...d.data() })).sort((a, b) => String(a.templeName).localeCompare(String(b.templeName))); const selected = state.memberships.find((m) => m.templeId === state.activeMembership?.templeId) || state.memberships[0] || null; if (snap.metadata.hasPendingWrites && !state.activeMembership) { renderWorkspace(); return; } if (selected?.templeId !== state.activeMembership?.templeId || selected?.role !== state.activeMembership?.role) activateTemple(selected); else renderWorkspace(); if (!selected) { elements.loading.classList.add("hidden"); showScreen("temple"); } }, firestoreError); }
function firestoreError(error) { console.error(error); elements.loading.classList.add("hidden"); toast(error.code === "permission-denied" ? t("cloudDenied") : t("cloudLoad"), "error"); }

async function initialize() { if (!firebaseConfigured()) { elements.configBanner.classList.add("show"); elements.loading.classList.add("hidden"); return; } try { const [appModule, fire, auth] = await Promise.all([import(`${FIREBASE_BASE}/firebase-app.js`), import(`${FIREBASE_BASE}/firebase-firestore.js`), import(`${FIREBASE_BASE}/firebase-auth.js`)]); const app = appModule.initializeApp(firebaseConfig); let db; try { db = fire.initializeFirestore(app, { localCache: fire.persistentLocalCache({ tabManager: fire.persistentMultipleTabManager() }) }); } catch { db = fire.getFirestore(app); } state.db = db; state.auth = auth.getAuth(app); state.f = { ...fire, ...auth }; await auth.setPersistence(state.auth, auth.browserLocalPersistence); auth.onAuthStateChanged(state.auth, (user) => { state.user = user; renderAccount(); clearWorkspaceListeners(); if (state.membershipUnsubscribe) { state.membershipUnsubscribe(); state.membershipUnsubscribe = null; } if (user) { elements.loading.classList.remove("hidden"); subscribeMemberships(); if ($("#account-screen").classList.contains("active")) showScreen("temple"); } else { state.memberships = []; state.activeMembership = null; renderWorkspace(); elements.loading.classList.add("hidden"); showScreen("account"); } }); } catch (error) { console.error(error); elements.loading.classList.add("hidden"); toast(t("firebaseStartError"), "error"); } }
async function googleSignIn() { const button = $("#google-signin-button"); busy(button, true, t("openingGoogle")); try { const provider = new state.f.GoogleAuthProvider(); provider.setCustomParameters({ prompt: "select_account" }); await state.f.signInWithPopup(state.auth, provider); } catch (error) { console.error("Google sign-in error:", error.code, error.message); const messages = { "auth/operation-not-allowed": "Google login is not enabled in Firebase Authentication.", "auth/api-key-not-valid.-please-pass-a-valid-api-key.": "The Firebase API key is incorrect. Copy the configuration again from Firebase Project Settings.", "auth/unauthorized-domain": "This website domain is not authorized in Firebase.", "auth/popup-blocked": "The browser blocked the Google login popup. Allow popups and try again.", "auth/popup-closed-by-user": "Google login was cancelled.", "auth/network-request-failed": "Network error. Check your internet connection and try again.", "auth/account-exists-with-different-credential": "This email already uses another login method." }; toast(messages[error.code] || `Google sign-in failed (${error.code || "unknown error"}).`, "error"); } finally { busy(button, false); } }
async function createTemple(event) { event.preventDefault(); const button = event.submitter; const name = String(new FormData(event.currentTarget).get("templeName")).trim(); if (!name) return; busy(button, true, t("creating")); try { const templeRef = state.f.doc(state.f.collection(state.db, "temples")); const memberRef = state.f.doc(state.db, "memberships", membershipId(state.user.uid, templeRef.id)); const batch = state.f.writeBatch(state.db); batch.set(templeRef, { name, ownerUid: state.user.uid, createdAt: state.f.serverTimestamp() }); batch.set(memberRef, { uid: state.user.uid, templeId: templeRef.id, templeName: name, displayName: state.user.displayName || "", email: state.user.email || "", role: "owner", createdAt: state.f.serverTimestamp() }); await batch.commit(); event.currentTarget.reset(); toast(t("created"), "success"); } catch (error) { console.error(error); toast(t("createFailed"), "error"); } finally { busy(button, false); } }
async function requestAccess(event) { event.preventDefault(); const button = event.submitter; const tid = String(new FormData(event.currentTarget).get("templeId")).trim(); busy(button, true, t("sending")); try { const templeSnap = await state.f.getDoc(state.f.doc(state.db, "temples", tid)); if (!templeSnap.exists()) throw new Error("not-found"); if (state.memberships.some((m) => m.templeId === tid)) throw new Error("already-member"); await state.f.setDoc(state.f.doc(state.db, "temples", tid, "joinRequests", state.user.uid), { uid: state.user.uid, displayName: state.user.displayName || "", email: state.user.email || "", requestedAt: state.f.serverTimestamp() }); event.currentTarget.reset(); toast(t("accessSent"), "success"); } catch (error) { console.error(error); toast(error.message === "not-found" ? t("notFound") : error.message === "already-member" ? t("alreadyMember") : t("requestFailed"), "error"); } finally { busy(button, false); } }
async function approveRequest(uid, role) { const request = state.requests.find((x) => x.uid === uid); if (!request || !isOwner()) return; const tid = state.activeMembership.templeId; try { const batch = state.f.writeBatch(state.db); batch.set(state.f.doc(state.db, "memberships", membershipId(uid, tid)), { uid, templeId: tid, templeName: state.activeMembership.templeName, displayName: request.displayName || "", email: request.email || "", role, createdAt: state.f.serverTimestamp() }); batch.delete(state.f.doc(state.db, "temples", tid, "joinRequests", uid)); await batch.commit(); toast(`${t("approved")} ${displayRole(role)}.`, "success"); } catch (error) { console.error(error); toast(t("approveFailed"), "error"); } }
async function renameTemple(event) { event.preventDefault(); if (!isOwner()) return; const button = event.submitter; const newName = String(new FormData(event.currentTarget).get("templeName")).trim(); if (!newName) return; if (newName === state.activeMembership.templeName) { toast(t("sameName")); return; } busy(button, true, t("saving")); const templeId = state.activeMembership.templeId; try { const membershipSnapshot = await state.f.getDocs(state.f.query(state.f.collection(state.db, "memberships"), state.f.where("templeId", "==", templeId))); const documents = membershipSnapshot.docs; for (let start = 0; start < documents.length; start += 400) { const batch = state.f.writeBatch(state.db); if (start === 0) batch.update(state.f.doc(state.db, "temples", templeId), { name: newName }); documents.slice(start, start + 400).forEach((document) => batch.update(document.ref, { templeName: newName })); await batch.commit(); } if (!documents.length) await state.f.updateDoc(state.f.doc(state.db, "temples", templeId), { name: newName }); state.activeMembership.templeName = newName; state.memberships.forEach((membership) => { if (membership.templeId === templeId) membership.templeName = newName; }); renderWorkspace(); toast(t("nameUpdated"), "success"); } catch (error) { console.error(error); toast(t("nameFailed"), "error"); } finally { busy(button, false); } }
async function changeMemberRole(memberId, role) { if (!isOwner() || !["admin", "viewer"].includes(role)) return; const member = state.members.find((item) => item.id === memberId); if (!member || member.role === "owner") return; try { await state.f.updateDoc(state.f.doc(state.db, "memberships", memberId), { role }); toast(`${member.displayName || member.email || t("member")} ${t("roleChanged")}`, "success"); } catch (error) { console.error(error); toast(t("roleFailed"), "error"); renderWorkspace(); } }
async function removeMember(memberId) { if (!isOwner()) return; const member = state.members.find((item) => item.id === memberId); if (!member || member.role === "owner") return; if (!confirm(`${member.displayName || member.email || t("member")} ${t("removeConfirm")}`)) return; try { await state.f.deleteDoc(state.f.doc(state.db, "memberships", memberId)); toast(t("removed"), "success"); } catch (error) { console.error(error); toast(t("removeFailed"), "error"); } }
function resetChanda() { state.editingChandaId = null; elements.chandaForm.reset(); $("#chanda-date").value = today(); elements.chandaCancel.classList.add("hidden"); applyLanguage(); }
function resetKharcha() { state.editingKharchaId = null; elements.kharchaForm.reset(); $("#kharcha-date").value = today(); elements.kharchaCancel.classList.add("hidden"); applyLanguage(); }
async function saveChanda(event) { event.preventDefault(); if (!canEdit()) return; const button = event.submitter; const data = new FormData(event.currentTarget); const amount = Number(data.get("amount")); if (!(amount > 0)) return toast(t("validAmount"), "error"); const record = { donorName: String(data.get("donorName")).trim(), amount, date: timestampFromInput(data.get("date")), paymentMode: String(data.get("paymentMode")), note: String(data.get("note")).trim() }; busy(button, true, t("saving")); try { const base = ["temples", state.activeMembership.templeId, "chanda"]; if (state.editingChandaId) await state.f.updateDoc(state.f.doc(state.db, ...base, state.editingChandaId), record); else await state.f.addDoc(state.f.collection(state.db, ...base), { ...record, createdAt: state.f.serverTimestamp(), createdBy: state.user.uid }); resetChanda(); toast(t("chandaSaved"), "success"); } catch (error) { console.error(error); toast(t("chandaSaveFailed"), "error"); } finally { busy(button, false); } }
async function saveKharcha(event) { event.preventDefault(); if (!canEdit()) return; const button = event.submitter; const data = new FormData(event.currentTarget); const amount = Number(data.get("amount")); if (!(amount > 0)) return toast(t("validAmount"), "error"); const record = { description: String(data.get("description")).trim(), amount, date: timestampFromInput(data.get("date")), category: String(data.get("category")), note: String(data.get("note")).trim() }; busy(button, true, t("saving")); try { const base = ["temples", state.activeMembership.templeId, "kharcha"]; if (state.editingKharchaId) await state.f.updateDoc(state.f.doc(state.db, ...base, state.editingKharchaId), record); else await state.f.addDoc(state.f.collection(state.db, ...base), { ...record, createdAt: state.f.serverTimestamp(), createdBy: state.user.uid }); resetKharcha(); toast(t("kharchaSaved"), "success"); } catch (error) { console.error(error); toast(t("kharchaSaveFailed"), "error"); } finally { busy(button, false); } }
async function handleEntryAction(event, type) { const button = event.target.closest("button[data-action]"); if (!button || !canEdit()) return; const isChanda = type === "chanda"; const entry = (isChanda ? state.chanda : state.kharcha).find((x) => x.id === button.dataset.id); if (!entry) return; if (button.dataset.action.startsWith("edit")) { if (isChanda) { state.editingChandaId = entry.id; $("#donor-name").value = entry.donorName || ""; $("#chanda-amount").value = entry.amount || ""; $("#chanda-date").value = inputDate(entry.date); $("#payment-mode").value = entry.paymentMode || "Cash"; $("#chanda-note").value = entry.note || ""; elements.chandaCancel.classList.remove("hidden"); elements.chandaAdminPanel.scrollIntoView({ behavior: "smooth" }); } else { state.editingKharchaId = entry.id; $("#expense-description").value = entry.description || ""; $("#kharcha-amount").value = entry.amount || ""; $("#kharcha-date").value = inputDate(entry.date); $("#expense-category").value = entry.category || "Other"; $("#kharcha-note").value = entry.note || ""; elements.kharchaCancel.classList.remove("hidden"); elements.kharchaAdminPanel.scrollIntoView({ behavior: "smooth" }); } applyLanguage(); } else if (button.dataset.action.startsWith("delete") && confirm(t("deleteConfirm"))) { try { await state.f.deleteDoc(state.f.doc(state.db, "temples", state.activeMembership.templeId, type, entry.id)); toast(t("entryDeleted"), "success"); } catch (error) { console.error(error); toast(t("deleteFailed"), "error"); } } }

elements.langButtons.forEach((button) => button.addEventListener("click", () => setLanguage(button.dataset.lang)));
elements.navButtons.forEach((button) => button.addEventListener("click", () => showScreen(button.dataset.screen)));
elements.accountButton.addEventListener("click", () => showScreen(state.user ? "temple" : "account"));
$("#google-signin-button").addEventListener("click", googleSignIn);
elements.logoutButton.addEventListener("click", async () => { await state.f.signOut(state.auth); toast(t("signedOut"), "success"); });
elements.createTempleForm.addEventListener("submit", createTemple); elements.joinTempleForm.addEventListener("submit", requestAccess); elements.renameTempleForm.addEventListener("submit", renameTemple);
elements.templeSwitcher.addEventListener("click", (event) => { const button = event.target.closest("button[data-temple-id]"); if (button) activateTemple(state.memberships.find((m) => m.templeId === button.dataset.templeId)); });
$("#copy-workspace-id").addEventListener("click", async () => { try { await navigator.clipboard.writeText(state.activeMembership.templeId); toast(t("copied"), "success"); } catch { toast(`Workspace ID: ${state.activeMembership.templeId}`); } });
elements.membersList.addEventListener("change", (event) => { const select = event.target.closest('select[data-action="change-role"]'); if (select) changeMemberRole(select.dataset.memberId, select.value); });
elements.membersList.addEventListener("click", (event) => { const button = event.target.closest('button[data-action="remove-member"]'); if (button) removeMember(button.dataset.memberId); });
elements.requestsList.addEventListener("click", async (event) => { const button = event.target.closest("button[data-action]"); if (!button) return; if (button.dataset.action === "approve") await approveRequest(button.dataset.uid, button.dataset.role); if (button.dataset.action === "reject" && confirm(t("rejectConfirm"))) await state.f.deleteDoc(state.f.doc(state.db, "temples", state.activeMembership.templeId, "joinRequests", button.dataset.uid)); });
elements.chandaForm.addEventListener("submit", saveChanda); elements.kharchaForm.addEventListener("submit", saveKharcha); elements.chandaCancel.addEventListener("click", resetChanda); elements.kharchaCancel.addEventListener("click", resetKharcha);
elements.chandaList.addEventListener("click", (event) => handleEntryAction(event, "chanda")); elements.kharchaList.addEventListener("click", (event) => handleEntryAction(event, "kharcha")); elements.chandaSearch.addEventListener("input", renderChanda); elements.kharchaSearch.addEventListener("input", renderKharcha);
function onlineStatus() { elements.offlineBanner.classList.toggle("show", !navigator.onLine); }
window.addEventListener("online", () => { onlineStatus(); toast(t("backOnline"), "success"); }); window.addEventListener("offline", onlineStatus); onlineStatus();
if ("serviceWorker" in navigator) window.addEventListener("load", () => navigator.serviceWorker.register("./service-worker.js").catch(console.warn));
resetChanda(); resetKharcha(); applyLanguage(); initialize();
